version: 2.1
orbs:
  orb-tools: circleci/orb-tools@9
  sonarcloud: checkmarx-ts/cxflow@dev:alpha
      
workflows:
  publish-dev:
    jobs:
      - orb-tools/pack:
          source-dir: src
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
      - orb-tools/publish-dev:
          context: Publishing Orb
          orb-name: checkmarx-ts/cxflow
          requires: [orb-tools/pack]
      - orb-tools/publish:
          context: Publishing Orb
          orb-ref: checkmarx-ts/cxflow@1.0.1
          attach-workspace: true
          filters:
            branches:
              only: master