description: >
  This is a sample executor using CxFlow TS Docker image.
docker:
  - image: 'checkmarxts/cxflow:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific checkmarx/cxflow image variant:
      https://hub.docker.com/r/checkmarxts/cxflow/tags
    type: string
